language: c
services: docker
jobs:
  include:
    - stage: nodejs
    script: ./scripts/travis/run.sh 8
    script: ./scripts/travis/run.sh
    script: ./scripts/travis/run.sh 10
    script: ./scripts/travis/run.sh 11
    script: ./scripts/travis/run.sh 12

