language: c
services: docker
jobs:
  include:
   - script: ./scripts/travis/run.sh 8
   - script: ./scripts/travis/run.sh 9
   - script: ./scripts/travis/run.sh 10
   - script: ./scripts/travis/run.sh 11
   - script: ./scripts/travis/run.sh 12


